import org.jetbrains.kotlin.gradle.plugin.mpp.pm20.targets

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.0.2/userguide/building_java_projects.html
 */

buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
        google()
    }
    dependencies {
        classpath("com.squareup.sqldelight:gradle-plugin:1.5.0")
    }
}

version = "1.0.0"
group = "com.github.dependables"

sqldelight {
    database("CacheDatabase") { // This will be the name of the generated database class.
        packageName = "de.unisaarland.caches"
    }
}

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.5.21"

    id("com.squareup.sqldelight") version "1.5.0"
    // Apply the java-library plugin for API and implementation separation.
    `java-library`

    `maven-publish`
}

repositories {
    maven("https://jitpack.io")

    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

apply {
    plugin("maven-publish")
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation("com.google.guava:guava:30.0-jre")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api("org.apache.commons:commons-math3:3.6.1")

    // PCDF core
    implementation("com.github.dependables:pcdf-core:1.0.1")

    implementation("com.squareup.sqldelight:sqlite-driver:1.5.0")
}

configure<PublishingExtension> {
    //publishing {
        publications {
            create<MavenPublication>("pcdfanalyser") {
                from(components["java"])
            }
        }
    //}
}
